# Configuration for a plugin published to npm
[[plugins]]
 package = "@netlify/plugin-lighthouse"
 
  # [plugins.inputs]
  # output_path = "reports/lighthouse.html"

  [[plugins.inputs.audits]]
    path = "/"
    output_path="reports/index.html"
  [[plugins.inputs.audits]]
    path = "/slider.html"
    output_path = "reports/slider.html"
  [[plugins.inputs.audits]]
    path = "/sous-dossier/autre.html"
    output_path = "reports/sous-dossier/autre.html"
