# Configuration for a plugin published to npm
[[plugins]]
 package = "@netlify/plugin-lighthouse"
 
  # [plugins.inputs]
  # output_path = "reports/lighthouse.html"

  [[plugins.inputs.audits]]
    # output_path="reports/index.html"
    path = ""

  [[plugins.inputs.audits]]
    # output_path = "reports/slider.html"
    path = "slider.html"
    
  [[plugins.inputs.audits]]
    output_path = "reports/sous-dossier/autre.html"
    path = "/sous-dossier/autre.html"
